-- Spec 03 — seed de órdenes de trabajo de desarrollo (REQ-44). Solo se carga en
-- el perfil "dev" (application.yml suma db/seed a spring.flyway.locations ahí
-- y solo ahí): nunca debe llegar a un entorno productivo.
--
-- Replica "work-orders" de db.json del frontend, generado con un script de una
-- sola vez (no se tipeó a mano). Reglas:
--   * ids 1 a 29 tal cual; las tres órdenes de id alfanumérico de db.json
--     (las últimas tres, todas pending) pasan a 30, 31 y 32, en el orden de db.json;
--   * los createdAt que db.json guarda sin zona horaria se interpretan como UTC;
--   * los dueños y autores de cierre "2" y "5" del frontend quedan a nombre de los
--     usuarios tecnico y electricista del backend (sus ids no coinciden con los del
--     frontend); los nombres se conservan de db.json;
--   * machineRef apunta a los ids de machines y parts de V6_1, que conservan los de
--     db.json.

INSERT INTO work_orders (id, title, description, machine_id, part_id, breadcrumb, machine_comment,
                         type, priority, status, created_at,
                         taken_by_id, taken_by_name, taken_at,
                         closing_comment, closing_author_id, closing_author_name, closed_at) VALUES
    (1, 'Revisar motor principal', 'El motor presenta vibraciones fuera del rango normal.', 1, NULL, 'Envasadora línea 1', 'Falla reportada en el punto indicado; revisar antes de reanudar la línea.', 'correctivo', 'medium', 'pending', '2026-08-01T10:30:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (2, 'Cambio de filtro hidráulico', 'Realizar el cambio preventivo del filtro.', 1, 1, 'Envasadora línea 1 > Mesa de transporte', '', 'preventivo', 'medium', 'in-progress', '2026-08-02T08:15:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-02T09:15:00.000Z', NULL, NULL, NULL, NULL),
    (3, 'Inspección de tablero eléctrico', 'Verificar conexiones y temperatura de componentes.', 1, 3, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta', '', 'preventivo', 'low', 'completed', '2026-08-03T14:00:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-03T15:00:00.000Z', 'Se reemplazó el rodamiento y se verificó el giro sin vibración ni ruido anormal.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-03T20:00:00.000Z'),
    (4, 'Reemplazo de rodamiento', 'Se detectó ruido anormal en el rodamiento.', 1, 4, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta > Rodamiento delantero', 'Falla reportada en el punto indicado; revisar antes de reanudar la línea.', 'correctivo', 'high', 'pending', '2026-08-04T09:20:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (5, 'Lubricación de cadena', 'Realizar lubricación preventiva de la cadena.', 1, 7, 'Envasadora línea 1 > Cabezal de sellado > Resistencia', '', 'preventivo', 'low', 'completed', '2026-08-05T11:45:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-05T12:45:00.000Z', 'Se lubricaron las guías y se ajustó la tensión de la cinta; queda funcionando dentro de rango.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-05T17:45:00.000Z'),
    (6, 'Control de temperatura', 'Verificar temperatura de operación del equipo.', 2, NULL, 'Selladora', '', 'preventivo', 'medium', 'in-progress', '2026-08-06T07:30:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-06T08:30:00.000Z', NULL, NULL, NULL, NULL),
    (7, 'Ajuste de correas', 'Las correas presentan pérdida de tensión.', 2, 9, 'Selladora > Cabezal térmico > Resistencia', 'Falla reportada en el punto indicado; revisar antes de reanudar la línea.', 'correctivo', 'medium', 'pending', '2026-08-07T13:10:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (8, 'Inspección de bomba', 'Controlar posibles pérdidas y presión de trabajo.', 2, 10, 'Selladora > Mordaza', '', 'preventivo', 'high', 'in-progress', '2026-08-08T15:25:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-08T16:25:00.000Z', NULL, NULL, NULL, NULL),
    (9, 'Limpieza de sensores', 'Realizar limpieza y verificación de sensores.', 3, NULL, 'Rotuladora', '', 'preventivo', 'low', 'cancelled', '2026-08-09T10:00:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-09T11:00:00.000Z', 'Se canceló la orden: el equipo estaba fuera de servicio por parada programada y se reprograma.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-09T16:00:00.000Z'),
    (10, 'Revisión de contactores', 'Verificar desgaste de contactos eléctricos.', 1, NULL, 'Envasadora línea 1', '', 'preventivo', 'medium', 'pending', '2026-08-10T08:40:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (11, 'Cambio de aceite', 'Realizar cambio de aceite según mantenimiento preventivo.', 1, 1, 'Envasadora línea 1 > Mesa de transporte', '', 'preventivo', 'medium', 'completed', '2026-08-11T12:00:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-11T13:00:00.000Z', 'Se limpiaron los contactos del tablero y se ajustó el apriete de las borneras; sin temperatura anormal.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-11T18:00:00.000Z'),
    (12, 'Verificar presión neumática', 'La presión se encuentra por debajo del valor nominal.', 1, 3, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta', 'Parada de producción: intervención inmediata.', 'pronto-intervencion', 'high', 'completed', '2026-08-12T09:10:00Z', (SELECT id FROM users WHERE username = 'tecnico'), 'Técnico Mecánico de Guardia', '2026-08-12T10:10:00.000Z', 'Se completo satisfactoriamente la orden de trabajo', (SELECT id FROM users WHERE username = 'tecnico'), 'Técnico Mecánico de Guardia', '2026-09-25T17:06:46.225Z'),
    (13, 'Inspección de cilindro', 'Revisar posibles pérdidas en sellos.', 1, 4, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta > Rodamiento delantero', '', 'preventivo', 'medium', 'pending', '2026-08-13T14:30:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (14, 'Calibración de sensor', 'Realizar calibración del sensor de posición.', 1, 7, 'Envasadora línea 1 > Cabezal de sellado > Resistencia', '', 'preventivo', 'high', 'completed', '2026-08-14T11:00:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-14T12:00:00.000Z', 'Se reemplazaron las resistencias del cabezal y se calibró la temperatura de sellado.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-14T17:00:00.000Z'),
    (15, 'Revisión de válvula', 'La válvula presenta dificultad de apertura.', 2, NULL, 'Selladora', 'Falla reportada en el punto indicado; revisar antes de reanudar la línea.', 'correctivo', 'medium', 'pending', '2026-08-15T16:20:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (16, 'Cambio de fusibles', 'Reemplazar fusibles deteriorados.', 2, 9, 'Selladora > Cabezal térmico > Resistencia', 'Falla reportada en el punto indicado; revisar antes de reanudar la línea.', 'correctivo', 'high', 'pending', '2026-08-16T07:50:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (17, 'Alineación de motor', 'Realizar alineación entre motor y reductor.', 2, 10, 'Selladora > Mordaza', '', 'preventivo', 'high', 'in-progress', '2026-08-17T10:15:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-17T11:15:00.000Z', NULL, NULL, NULL, NULL),
    (18, 'Limpieza de ventilación', 'Retirar suciedad acumulada en rejillas.', 3, NULL, 'Rotuladora', '', 'preventivo', 'low', 'completed', '2026-08-18T13:30:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-18T14:30:00.000Z', 'Se inspeccionó el reductor, nivel de aceite correcto y sin pérdidas; se registra la lectura de vibración.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-18T19:30:00.000Z'),
    (19, 'Control de nivel de aceite', 'Verificar nivel y condición del lubricante.', 1, NULL, 'Envasadora línea 1', '', 'preventivo', 'low', 'pending', '2026-08-19T09:45:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (20, 'Revisión de encoder', 'El encoder presenta lecturas intermitentes.', 1, 1, 'Envasadora línea 1 > Mesa de transporte', 'Parada de producción: intervención inmediata.', 'pronto-intervencion', 'high', 'cancelled', '2026-08-20T15:10:00Z', (SELECT id FROM users WHERE username = 'tecnico'), 'Técnico Mecánico de Guardia', '2026-08-20T16:10:00.000Z', 'Se cancela por que la orden fue un error operativo , no hay reparacion', (SELECT id FROM users WHERE username = 'tecnico'), 'Técnico Mecánico de Guardia', '2026-09-25T17:07:32.137Z'),
    (21, 'Cambio de manguera hidráulica', 'Se detectó deterioro superficial en la manguera.', 1, 3, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta', 'Falla reportada en el punto indicado; revisar antes de reanudar la línea.', 'correctivo', 'high', 'in-progress', '2026-08-21T08:25:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-09-25T17:09:38.353Z', NULL, NULL, NULL, NULL),
    (22, 'Inspección de finales de carrera', 'Comprobar funcionamiento de finales de carrera.', 1, 4, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta > Rodamiento delantero', '', 'preventivo', 'medium', 'completed', '2026-08-22T12:40:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-22T13:40:00.000Z', 'Se verificó el sensor de posición, se limpió la lente y se recalibró; detección estable en las pruebas.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-22T18:40:00.000Z'),
    (23, 'Ajuste de acoplamiento', 'Verificar juego mecánico y ajustar acoplamiento.', 1, 7, 'Envasadora línea 1 > Cabezal de sellado > Resistencia', '', 'preventivo', 'medium', 'in-progress', '2026-08-23T10:20:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-23T11:20:00.000Z', NULL, NULL, NULL, NULL),
    (24, 'Revisión de resistencia', 'Medir resistencia eléctrica y verificar aislamiento.', 2, NULL, 'Selladora', '', 'preventivo', 'high', 'pending', '2026-08-24T14:55:00Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (25, 'Limpieza de filtro de aire', 'Limpiar filtro y verificar caudal.', 2, 9, 'Selladora > Cabezal térmico > Resistencia', '', 'preventivo', 'low', 'completed', '2026-08-25T09:35:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-25T10:35:00.000Z', 'Se cambiaron las correas y se alineó la polea; funcionamiento normal tras la marcha de prueba.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-25T15:35:00.000Z'),
    (26, 'Control de vibraciones', 'Medir vibraciones y comparar con valores históricos.', 2, 10, 'Selladora > Mordaza', '', 'preventivo', 'medium', 'in-progress', '2026-08-26T11:10:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-26T12:10:00.000Z', NULL, NULL, NULL, NULL),
    (27, 'Reemplazo de sensor inductivo', 'El sensor no detecta correctamente la pieza.', 3, NULL, 'Rotuladora', 'Parada de producción: intervención inmediata.', 'pronto-intervencion', 'high', 'in-progress', '2026-08-27T13:25:00Z', (SELECT id FROM users WHERE username = 'tecnico'), 'Técnico Mecánico de Guardia', '2026-09-25T17:07:45.737Z', NULL, NULL, NULL, NULL),
    (28, 'Inspección de seguridad', 'Verificar protecciones y dispositivos de seguridad.', 1, NULL, 'Envasadora línea 1', '', 'preventivo', 'high', 'completed', '2026-08-28T08:05:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-28T09:05:00.000Z', 'Se realizó la inspección programada completa según el plan y no se encontraron desvíos.', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-28T14:05:00.000Z'),
    (29, 'Ajuste de presión', 'Regular presión de trabajo según especificación.', 1, 1, 'Envasadora línea 1 > Mesa de transporte', '', 'preventivo', 'medium', 'in-progress', '2026-08-29T16:10:00Z', (SELECT id FROM users WHERE username = 'electricista'), 'Técnico Electricista Preventivo', '2026-08-29T17:10:00.000Z', NULL, NULL, NULL, NULL),
    (30, 'Reparar rodamiento de mesa 1', 'Reparar rodamiento', 1, 4, 'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta > Rodamiento delantero', '', 'correctivo', 'medium', 'pending', '2026-09-25T17:02:43.490Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (31, 'orden test', 'orden test', 2, NULL, 'Selladora', '', 'correctivo', 'low', 'pending', '2026-09-25T17:04:39.137Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    (32, 'nueva orden test', 'no funcion maquina', 2, NULL, 'Selladora', '', 'pronto-intervencion', 'medium', 'pending', '2026-09-25T17:08:29.874Z', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- BIGSERIAL no avanza solo con ids explícitos: la próxima orden debe ser la 33.
SELECT setval(pg_get_serial_sequence('work_orders', 'id'), (SELECT MAX(id) FROM work_orders));

-- Se prefiere un arranque roto a un seed a medias: si un subselect de usuario dio NULL,
-- una orden en progreso o cerrada quedaría sin dueño o sin autor de cierre.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM work_orders WHERE status <> 'pending' AND taken_by_id IS NULL) THEN
        RAISE EXCEPTION 'Seed de órdenes incompleto: hay una orden no pending sin dueño';
    END IF;
    IF EXISTS (SELECT 1 FROM work_orders WHERE status IN ('completed', 'cancelled') AND closing_author_id IS NULL) THEN
        RAISE EXCEPTION 'Seed de órdenes incompleto: hay una orden cerrada sin autor de cierre';
    END IF;
END $$;
